before (() => {
    cy.login()
})

beforeEach(() => {
    cy.visit('localhost:4200')
    cy.wait(1000)
})

describe('Card Manipulation', function() {
    it('Click cards onto the board', function () {
        cy.viewport('macbook-16') 
        cy.get('#add-button').click()
        cy.get('#mat-input-0').type('testworkplace').should('have.value', 'testworkplace')
        cy.get('#mat-input-1').type('testgoal').should('have.value', 'testgoal')
        cy.get('#0')
        cy.get('button').contains('SAVE').click()
        cy.wait(1000)
        cy.get('mat-card').contains('testworkplace').should('be.visible')
        cy.get('app-workspace-card')
        cy.get('.mat-card-image').eq(-1).click()
        cy.get('#mat-dialog-0').should('be.visible')
        cy.get('li').click('left', { multiple: true})
        cy.get('button').contains('SAVE').click()
        cy.wait(1000)
        cy.get('button').contains('build').click()
        cy.get('#screen > mat-drawer > div > div.ng-star-inserted > img:nth-child(1)').should('be.visible').click()
        cy.get('#screen > mat-drawer > div > div.ng-star-inserted > img:nth-child(2)').should('be.visible').click()
        cy.get('img').eq(1).click()
        cy.get('app-card-selector-card').should('be.visible')
        cy.get('mat-card').contains('Document analysis').should('be.visible')
    })
    
    it('Drag cards from inspiration toolbar to a group', function () {
        cy.viewport('macbook-16') 
        cy.get('#add-button').click()
        cy.get('#mat-input-0').type('testworkplace').should('have.value', 'testworkplace')
        cy.get('#mat-input-1').type('testgoal').should('have.value', 'testgoal')
        cy.get('#0')
        cy.get('button').contains('SAVE').click()
        cy.wait(1000)
        cy.get('mat-card').contains('testworkplace').should('be.visible')
        cy.get('app-workspace-card')
        cy.get('.mat-card-image').eq(-1).click()
        cy.get('#mat-dialog-0').should('be.visible')
        cy.get('li').click('left', { multiple: true})
        cy.get('button').contains('SAVE').click()
        cy.wait(1000)
        cy.get('button').contains('build').click()
        cy.get('#screen > mat-drawer > div > div.ng-star-inserted > img:nth-child(1)').should('be.visible').click()
        cy.get('img').eq(1).click()
        cy.get('app-card-selector-card').should('be.visible')
        cy.get('mat-card').eq(0).should('be.visible').drag('.group-content').then((success) => {
            assert.isTrue(success)
        })
    })
    
    it('View card', function () {
        cy.viewport('macbook-16') 
        cy.get('#add-button').click()
        cy.get('#mat-input-0').type('testworkplace').should('have.value', 'testworkplace')
        cy.get('#mat-input-1').type('testgoal').should('have.value', 'testgoal')
        cy.get('#0')
        cy.get('button').contains('SAVE').click()
        cy.wait(1000)
        cy.get('mat-card').contains('testworkplace').should('be.visible')
        cy.get('app-workspace-card')
        cy.get('.mat-card-image').eq(-1).click()
        cy.get('#mat-dialog-0').should('be.visible')
        cy.get('li').click('left', { multiple: true})
        cy.get('button').contains('SAVE').click()
        cy.wait(1000)
        cy.get('img').eq(1).click()
        cy.get('app-card-selector-card').should('be.visible')
        cy.get('mat-card').contains('Document analysis').should('be.visible').click()
        cy.get('app-card').contains('Document analysis').should('be.visible').click()
        cy.get('mat-dialog-container').should('be.visible')
    })

    it('Remove cards from a group', function () {
        cy.viewport('macbook-16') 
        cy.get('#add-button').click()
        cy.get('#mat-input-0').type('testworkplace').should('have.value', 'testworkplace')
        cy.get('#mat-input-1').type('testgoal').should('have.value', 'testgoal')
        cy.get('#0')
        cy.get('button').contains('SAVE').click()
        cy.wait(1000)
        cy.get('mat-card').contains('testworkplace').should('be.visible')
        cy.get('app-workspace-card')
        cy.get('.mat-card-image').eq(-1).click()
        cy.get('#mat-dialog-0').should('be.visible')
        cy.get('li').click('left', { multiple: true})
        cy.get('button').contains('SAVE').click()
        cy.wait(1000)
        cy.get('button').contains('build').click()
        cy.get('#screen > mat-drawer > div > div.ng-star-inserted > img:nth-child(1)').should('be.visible').click()
        cy.get('img').eq(1).click()
        cy.get('app-card-selector-card').should('be.visible')
        cy.get('mat-card').eq(0).click()
        cy.get('app-card').eq(0).should('be.visible').drag('.group-content').then((success) => {
            assert.isTrue(success)
        })
        cy.get('app-card').eq(0).rightclick()
        cy.get('button').contains('Remove card').click()
    })

})